#!/bin/bash -l 
#SBATCH -A uppmax2024-2-7
#SBATCH -M snowy
#SBATCH -p core 
#SBATCH -n 2
#SBATCH -t 00:15:00
#SBATCH -J Quality_analysis_test
#SBATCH --mail-type=ALL
#SBATCH --mail-user gslottner@gmail.com

module load bioinfo-tools FastQC

export SRCDIR=$HOME/Genome_analysis_repo/Data
cp $SRCDIR/ 
cd $SNIC_TMP

bwa index ref.fa

cp *.out $SRCDIR/run_as_batch/output
